

export class SettingConstants {
    static ELECTRICITY_UNIT_PRICE = 'ELECTRICITY_UNIT_PRICE';
    static WATER_UNIT_PRICE = 'WATER_UNIT_PRICE';
    static START_DAY_OF_INVOICE = 'START_DAY_OF_INVOICE';
}